# Generated by Django 3.2.11 on 2022-01-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_paymentintent_alter_greeting_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdigiAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(blank=True, max_length=100)),
                ('postalOrZipCode', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=100)),
                ('townOrCity', models.CharField(max_length=100)),
                ('stateOrCounty', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiAuthorisationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorisationUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiCharge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prodigiInvoiceNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiChargeItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('itemSku', models.CharField(max_length=100)),
                ('shipmentId', models.CharField(max_length=100)),
                ('itemId', models.CharField(max_length=100)),
                ('merchantItemReference', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadAssets', models.CharField(choices=[('NotStarted', 'Notstarted'), ('InProgress', 'Inprogress'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=100)),
                ('allocateProductionLocation', models.CharField(choices=[('NotStarted', 'Notstarted'), ('InProgress', 'Inprogress'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=100)),
                ('printReadyAssetsPrepared', models.CharField(choices=[('NotStarted', 'Notstarted'), ('InProgress', 'Inprogress'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=100)),
                ('inProduction', models.CharField(choices=[('NotStarted', 'Notstarted'), ('InProgress', 'Inprogress'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=100)),
                ('shipping', models.CharField(choices=[('NotStarted', 'Notstarted'), ('InProgress', 'Inprogress'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiFulfillmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(max_length=100)),
                ('labCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.CharField(max_length=100)),
                ('errorCode', models.CharField(choices=[('items.assets.NotDownloaded', 'Items.Assets.Notdownloaded'), ('items.assets.FailedToDownloaded', 'Items.Assets.Failedtodownloaded')], max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('merchantReference', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('copies', models.IntegerField()),
                ('sizing', models.CharField(max_length=100)),
                ('attributes', models.JSONField(blank=True)),
                ('assets', models.ManyToManyField(to='hello.ProdigiAsset')),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiPackingSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printArea', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiShipmentItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiShipment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('carrier', models.CharField(max_length=100)),
                ('tracking', models.CharField(max_length=100)),
                ('dispatchDate', models.CharField(max_length=100)),
                ('fulfillmentLocation', models.CharField(blank=True, max_length=100)),
                ('items', models.ManyToManyField(to='hello.ProdigiChargeItem')),
            ],
        ),
        migrations.CreateModel(
            name='ProdigiOrder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created', models.CharField(max_length=100)),
                ('callbackUrl', models.CharField(blank=True, max_length=100)),
                ('merchantReference', models.CharField(blank=True, max_length=100)),
                ('shippingMethod', models.CharField(max_length=100)),
                ('idempotencyKey', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField()),
                ('charges', models.ManyToManyField(to='hello.ProdigiCharge')),
                ('items', models.ManyToManyField(to='hello.ProdigiItem')),
                ('shipments', models.ManyToManyField(to='hello.ProdigiShipment')),
            ],
        ),
        migrations.AddField(
            model_name='prodigicharge',
            name='items',
            field=models.ManyToManyField(to='hello.ProdigiChargeItem'),
        ),
    ]
